name: build

on:
  push:
    tags:
      - '*'
jobs:
  xgo:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin]
        arch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: crazy-max/ghaction-xgo@v2
        with:
          xgo_version: latest
          go_version: '1.20'
          dest: build
          prefix: ggt
          targets: ${{ matrix.os }}/${{ matrix.arch }}
          v: true
          x: false
          race: false
          ldflags: -s -w
          buildmode: default
          trimpath: true
          pkg: main.go
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/ggt-${{ matrix.os }}-${{ matrix.arch }}*
