name: build

on:
  push:
    tags:
      - '*'
jobs:
  xgo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: crazy-max/ghaction-xgo@v3
        with:
          xgo_version: latest
          go_version: '1.23'
          dest: build
          prefix: ggt
          targets: windows/amd64,linux/amd64,linux/arm64,darwin/arm64
          v: true
          x: false
          race: false
          ldflags: -s -w
          buildmode: default
          trimpath: true
          pkg: cmd/*
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/ggt-windows-amd64*
            build/ggt-linux-amd64*
            build/ggt-linux-arm64*
            build/ggt-darwin-arm64*
